version: "3.9"
services:
  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  web:
    build: ./onboarding-portal-webapp
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=PathPrefix(`/portal`)"
      - "traefik.http.middlewares.strip-pre.stripprefix.prefixes=/portal,/api"
      - "traefik.http.routers.web.middlewares=strip-pre"
      - "traefik.http.routers.web.entrypoints=web"
    environment:
      - CMS_API_URL=http://backend:1337
      - MOCK_API_RESPONSES=false
      - "PATH_PREFIX=/portal"
  backend:
    build: ./vigilant-dollop
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.priority=99"
      - "traefik.http.routers.api.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.api.middlewares=strip-pre"
      - "traefik.http.routers.api.entrypoints=web"
    environment:
      - DATABASE_HOST=host.docker.internal
      - STRAPI_URL=http://localhost/api
